baseurl = "http://118.126.104.235/" 
title = "主机售后平台 v1.0"
theme = "hugo-universal-theme"
themesDir = "/opt/mysite/themes/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false


[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "雷神路由器"
    identifier = "menu.features"
    url        = "/img/luyouqi.png"
    weight     = 3

[[menu.main]]
    name       = "雷神路由器"
    identifier = "section.features"
    url        = "/blog/20241212/luyouqi-common-problem/"
    weight     = 1
    parent     = "menu.features"
    post       = 1

[[menu.main]]
    name       = "路由器常见问题"
    url        = "http://118.126.104.235/blog/20241212/luyouqi-common-problem/"
    weight     = 2
    parent     = "section.features"

[[menu.main]]
    name       = "雷神加速盒"
    identifier = "menu.portfolio"
    url        = "/img/jiasuhe.png"
    weight     = 3

[[menu.main]]
    name       = "雷神加速盒"
    identifier = "section.portfolio"
    url        = "http://118.126.104.235/blog/20241212/jiasuhe-common-problem/"
    weight     = 2
    parent     = "menu.portfolio"
    post       = 1

[[menu.main]]
    name       = "加速盒常见问题"
    url        = "http://118.126.104.235/blog/20241212/jiasuhe-common-problem/"
    weight     = 2
    parent     = "section.portfolio"

[[menu.main]]
    name       = "手机中转加速"
    identifier = "menu.allpages"
    url        = ""
    weight     = 4

[[menu.main]]
    name       = "手机中转加速"
    identifier = "section.ap-home"
    url        = ""
    weight     = 1
    parent     = "menu.allpages"
    post       = 3

[[menu.main]]
    name       = "手机中转加速常见问题"
    url        = "http://118.126.104.235/blog/20241212/zhongzhuanjiasu-common-problem/"
    weight     = 2
    parent     = "section.ap-home"



#[[menu.main]]
#    name       = "Blog"
#    identifier = "menu.blog"
#    url        = "/blog/"
#    weight     = 5

[[menu.main]]
    name       = "紧急问题处理公告"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 1

[[menu.main]]
    identifier = "contact"
    name       = "寄修地址"
    url        = "/contact/"
    weight     = 6




# Top bar social links menu
[params]
    homepage = "index"
    viewMorePostLink = "/blog/"
    author = "陶某人"
    defaultKeywords = ["go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by 陶某人  using Hugo"

    # Social media
    #facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    #twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    #default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = ""
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

   # about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = true
    logo_text = "主机售后平台"

    logo = "img/newlogo.png"
    logo_small = "img/newlogo-small.png"
    contact_url = "/contact"

[permalinks]
    blog = "/blog/:year:month:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
